
sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan duty cycle"
  register_type: holding
  address: 0x137
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  id: zehnder_supply_duty
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan duty cycle"
  register_type: holding
  address: 0x136
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  id: zehnder_exhaust_duty
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan air flow"
  register_type: holding
  address: 0x139
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  id: zehnder_supply_flow
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan air flow"
  register_type: holding
  address: 0x138
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  id: zehnder_exhaust_flow

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan air speed"
  register_type: holding
  address: 0x13B
  unit_of_measurement: "RPM"
  value_type: U_WORD
  id: zehnder_supply_rpm
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan air speed"
  register_type: holding
  address: 0x13A
  unit_of_measurement: "RPM"
  value_type: U_WORD
  id: zehnder_exhaust_rpm

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Ventilation level"
  register_type: holding
  address: 0x14A
  unit_of_measurement: "%"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Outside air temperature"
  register_type: holding
  address: 0x12C
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: U_WORD
  id: zehnder_t1
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Pre-heater temperature"
  register_type: holding
  address: 0x12D
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: U_WORD
  id: zehnder_t2
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply air temperature"
  register_type: holding
  address: 0x12F
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: U_WORD
  id: zehnder_t4
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Extract air temperature"
  register_type: holding
  address: 0x130
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: U_WORD
  id: zehnder_t5
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust air temperature"
  register_type: holding
  address: 0x131
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: U_WORD
  id: zehnder_t6
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
