uart:
  id: uart_modbus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 19200
  data_bits: 8
  parity: EVEN
  stop_bits: 1

modbus:
  uart_id: uart_modbus
  id: modbus1
#  flow_control_pin: GPIOXX # used for the MAX485 chip without automatic flow control

modbus_controller:
- id: modbus_device
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10
  update_interval: ${update_interval}

sensor:
# --- fan states ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan duty cycle"
  register_type: holding
  address: 0x136
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  id: zehnder_exhaust_duty
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan duty cycle"
  register_type: holding
  address: 0x137
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  id: zehnder_supply_duty
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan flow rate"
  register_type: holding
  address: 0x138
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  state_class: "measurement"
  id: zehnder_exhaust_flow
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan flow rate"
  register_type: holding
  address: 0x139
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  state_class: "measurement"
  id: zehnder_supply_flow

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan speed"
  register_type: holding
  address: 0x13A
  unit_of_measurement: "RPM"
  value_type: U_WORD
  state_class: "measurement"
  id: zehnder_exhaust_rpm
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan speed"
  register_type: holding
  address: 0x13B
  unit_of_measurement: "RPM"
  value_type: U_WORD
  state_class: "measurement"
  id: zehnder_supply_rpm

# --- temperatures ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Outdoor air temperature"
  register_type: holding
  address: 0x12C
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t1
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Pre-heater temperature"
  register_type: holding
  address: 0x12D
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t2
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply air temperature"
  register_type: holding
  address: 0x12F
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t4
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Extract air temperature"
  register_type: holding
  address: 0x130
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t5
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust air temperature"
  register_type: holding
  address: 0x131
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t6
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1

# --- control setpoint ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "3-way switch control setpoint"
  id: zehnder_three_way_control_setpoint
  register_type: holding
  address: 0x14A
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "0-10 V control setpoint"
  id: zehnder_zero_ten_V_control_setpoint
  register_type: holding
  address: 0x148
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "RF control setpoint"
  id: zehnder_rf_control_setpoint
  register_type: holding
  address: 0x149
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "RF input voltage"
  id: zehnder_rf_input_voltage
  register_type: holding
  address: 0x13D
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.01

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan flow rate setpoint"
  id: zehnder_exhaust_flow_setpoint
  register_type: holding
  address: 0x141
  state_class: "measurement"
  value_type: U_WORD
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan flow rate setpoint"
  id: zehnder_supply_flow_setpoint
  register_type: holding
  address: 0x140
  state_class: "measurement"
  value_type: U_WORD
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"